export { fake } from './fake'
export * from './type'
export * from './fakers/base'
export * from './fakers/mixed'
export * from './fakers/array'
export * from './fakers/boolean'
export * from './fakers/date'
export * from './fakers/number'
export * from './fakers/object'
export * from './fakers/string'
export * from './version'
export * from './config'
